var graph = new joint.dia.Graph;

var paper = new joint.dia.Paper({
    el: $('#paper'),
    width: 3000,
    height: 3000,
    gridSize: 1,
    model: graph
});

var uml = joint.shapes.uml;

var states = {

HUB_Account: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "HUB_Account"}),
HUB_CampaignActivity: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "HUB_CampaignActivity"}),
HUB_CampaignProgram: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "HUB_CampaignProgram"}),
HUB_CampaignSegment: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "HUB_CampaignSegment"}),
HUB_Charge: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "HUB_Charge"}),
HUB_CoverType: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "HUB_CoverType"}),
HUB_CustomerCoverType: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "HUB_CustomerCoverType"}),
HUB_CustomerCoverTypeEvent: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "HUB_CustomerCoverTypeEvent"}),
HUB_CustomerCoverTypeOffer: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "HUB_CustomerCoverTypeOffer"}),
HUB_CustomerCoverTypeTerm: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "HUB_CustomerCoverTypeTerm"}),
HUB_CustomerCoverTypeValidity: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "HUB_CustomerCoverTypeValidity"}),
HUB_CustomerOffer: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "HUB_CustomerOffer"}),
HUB_CustomerProduct: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "HUB_CustomerProduct"}),
HUB_CustomerProductH1: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "HUB_CustomerProductH1"}),
HUB_CustomerProductH2: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "HUB_CustomerProductH2"}),
HUB_CustomerProductH3: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "HUB_CustomerProductH3"}),
HUB_Invoice: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "HUB_Invoice"}),
HUB_Partner: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "HUB_Partner"}),
HUB_Product: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "HUB_Product"}),
HUB_User: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "HUB_User"}),

HLNK_Account_HouseholdRelationship: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "HLNK_Account_HouseholdRelationship"}),
HLNK_Partner_Orga: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "HLNK_Partner_Orga"}),
HLNK_User_Orga: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "HLNK_User_Orga"}),
LNK_Account_CampaignActivity: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "LNK_Account_CampaignActivity"}),
LNK_Account_CampaignSegment: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "LNK_Account_CampaignSegment"}),
LNK_Bene_Head: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "LNK_Bene_Head"}),
LNK_CampaignActivity_CampaignProgram: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "LNK_CampaignActivity_CampaignProgram"}),
LNK_CampaignSegment_CampaignActivity: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "LNK_CampaignSegment_CampaignActivity"}),
LNK_CCT_CPR_CH3_CH2_CH1_Head_Bene_CT: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "LNK_CCT_CPR_CH3_CH2_CH1_Head_Bene_CT"}),
LNK_CCT_CPR_CH3_CH2_CH1_Head_Bene_CT_save: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "LNK_CCT_CPR_CH3_CH2_CH1_Head_Bene_CT_save"}),
LNK_CCTE_CCTT_CCTV_CCT_Beneficiary_CoverType_Product: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "LNK_CCTE_CCTT_CCTV_CCT_Beneficiary_CoverType_Product"}),
LNK_CCTOFF_CampaignActivity: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "LNK_CCTOFF_CampaignActivity"}),
LNK_CCTOFF_CampaignSegment: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "LNK_CCTOFF_CampaignSegment"}),
LNK_CCTOFF_COFF_Head_Bene_CT_CCTV_CCTT: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "LNK_CCTOFF_COFF_Head_Bene_CT_CCTV_CCTT"}),
LNK_CCTT_CCTV_CCT_Beneficiary_CoverType_Product: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "LNK_CCTT_CCTV_CCT_Beneficiary_CoverType_Product"}),
LNK_COFF_Partner: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "LNK_COFF_Partner"}),
LNK_COFF_User: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "LNK_COFF_User"}),
LNK_CoverType_Product: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "LNK_CoverType_Product"}),
LNK_CustomerCoverType_Account_Beneficiary: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "LNK_CustomerCoverType_Account_Beneficiary"}),
LNK_CustomerCoverType_Account_Head: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "LNK_CustomerCoverType_Account_Head"}),
LNK_CustomerCoverType_CoverType: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "LNK_CustomerCoverType_CoverType"}),
LNK_CustomerCoverType_Product: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "LNK_CustomerCoverType_Product"}),
LNK_CustomerCoverTypeEvent_CampaignActivity: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "LNK_CustomerCoverTypeEvent_CampaignActivity"}),
LNK_CustomerCoverTypeEvent_CampaignSegment: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "LNK_CustomerCoverTypeEvent_CampaignSegment"}),
LNK_CustomerCoverTypeEvent_Charge_Invoice: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "LNK_CustomerCoverTypeEvent_Charge_Invoice"}),
LNK_CustomerCoverTypeEvent_CustomerCoverType: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "LNK_CustomerCoverTypeEvent_CustomerCoverType"}),
LNK_CustomerCoverTypeEvent_CustomerCoverTypeTerm: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "LNK_CustomerCoverTypeEvent_CustomerCoverTypeTerm"}),
LNK_CustomerCoverTypeEvent_CustomerCoverTypeValidity: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "LNK_CustomerCoverTypeEvent_CustomerCoverTypeValidity"}),
LNK_CustomerCoverTypeTerm_CustomerCoverTypeValidity_CustomerCoverType: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "LNK_CustomerCoverTypeTerm_CustomerCoverTypeValidity_CustomerCoverType"}),
LNK_CustomerCoverTypeValidity_CustomerCoverType: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "LNK_CustomerCoverTypeValidity_CustomerCoverType"}),
LNK_Invoice_Account: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "LNK_Invoice_Account"}),

SAT_CURR_CustomerProductH2_SF: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "SAT_CURR_CustomerProductH2_SF",events: ["Seniority","InitialStartDate","SeniorityReconciled","InitialStartDateReconciled","FlagActive"]}),
SAT_CURR_Account_SF: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "SAT_CURR_Account_SF",events: ["TechId_Txt","CompleteName","LastName","FirstName","REFTranslation_Salutation","Gender","REFTranslation_Title","BirthDate","REFTranslation_Nationality","REFTranslation_Language","REFTranslation_Occupation","CustomerType","IsMember","REFTranslation_MemberSubtype","BlackListProducts","REFTranslation_BlackListReasonAssista","REFTranslation_BlackListReasonBackOffice","REFTranslation_BlackListReasonETI","REFTranslation_BlackListReasonFinance","BlackListReasonPayment","BorderCode","RobsinsonCode","SectionBlocking","ClubCampingBlocking","FlagCancMotif1","FlagMarketingEmail","FlagMarketingMail","FlagMarketingPhone","FlagCommercialEmail","REFTranslation_RegistrationStatus","DriveCourse","Mobility","LegalQuestions","SecurityAndTests","AddressBlocking","REFTranslation_ReasonForAddressBlocking","REFTranslation_HouseholdRelationship","REFTranslation_HouseholdCategory","REFTranslation_HouseholdRole","PhoneMobile","PhoneLandLine","PhoneProf","Fax","Email","REFTranslation_FavoriteMeanOfPayment","NewsletterSubscription","CarOwner","MotorbikeOwner","SecondAptOwner","MembersAdvantages","FlagDeleted"]}),
SAT_CURD_Account_BillingAddress_SF: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "SAT_CURD_Account_BillingAddress_SF",events: ["TechId_Txt","Tech_Name","ValidityStartdate","ValidityEnddate","IsActive","HasPostOfficeBox","PostOfficeBoxNumber","AdressComplement","AdressComplementCo","HouseNumber","HouseNumberComplement","StreetName","ZipCode","ZipCodeComplement","REFTranslation_ZipCodeLanguage","Locality","SwissAdress","REFTranslation_Country","Canton","FlagDeleted"]}),
SAT_CURD_Account_LegalAddress_SF: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "SAT_CURD_Account_LegalAddress_SF",events: ["TechId_Txt","Tech_Name","ValidityStartdate","ValidityEnddate","IsActive","HasPostOfficeBox","PostOfficeBoxNumber","AdressComplement","AdressComplementCo","HouseNumber","HouseNumberComplement","StreetName","ZipCode","ZipCodeComplement","REFTranslation_ZipCodeLanguage","Locality","SwissAdress","REFTranslation_Country","Canton","FlagDeleted"]}),
SAT_CURD_Account_SF: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "SAT_CURD_Account_SF",events: ["CampingClub","Section","Subsection","REFTranslation_Status","REFTranslation_Type","ValidityStartDate","ValidityEndDate"]}),
SAT_CURR_CustomerProductH3_SF: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "SAT_CURR_CustomerProductH3_SF",events: ["Seniority","InitialStartDate","FlagActive"]}),
SAT_CURR_CustomerCoverTypeEvent_SF: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "SAT_CURR_CustomerCoverTypeEvent_SF",events: ["EventDate","SubscribedProduct","CatalogPrice","TotalPrice","UnitPrice","NrVehicles","NrSubscribedProduct","TransactionType","SalesType","FlagDeleted"]}),
SAT_CURR_Product_Zuora: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "SAT_CURR_Product_Zuora",events: ["TechID_Txt","TechID","Description","SellingCompany","BillingCompany","SKU","StartDate","EndDate","Calc_IsMkt","FlagDeleted"]}),
SAT_CURR_CoverType_Zuora: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "SAT_CURR_CoverType_Zuora",events: ["TechID_Txt","TechID","Section","Subsection","StartDate","EndDate","Pack","Description","RefTranslation_MembershipType","RefTranslation_Variante","CodeCGA","RefTranslation_TypeProduit","AutoRenew","Calc_IsMkt","FlagDeleted"]}),
SAT_CURR_CustomerCoverTypeTerm_SF: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "SAT_CURR_CustomerCoverTypeTerm_SF",events: ["TermStartDate","TermEndDate","CreationEvent","VehicleNumber","ProductSection","CurrentStatus","SuspensionDate","hps_DatePaiementFacture__c","FlagDeleted"]}),
SAT_CURR_CustomerCoverTypeTerm_Zuora: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "SAT_CURR_CustomerCoverTypeTerm_Zuora",events: ["TermStartDate","TermEndDate","CreationEvent","ProductSection","VehicleNumber","FlagDeleted"]}),
SAT_CURR_User_SF: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "SAT_CURR_User_SF",events: ["TechID_Txt","Name","Description","FlagDeleted"]}),
SAT_CURR_CampaignSegment_SF: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "SAT_CURR_CampaignSegment_SF",events: ["TechId_Txt","TargetName","FlagDeleted"]}),
SAT_CURR_CampaignActivity_SF: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "SAT_CURR_CampaignActivity_SF",events: ["TechID_Txt","CAMCode","Name","REFTranslation_Fct_AprimoProduct","ProductSecondary_Desc_FRA","ProductSecondary_Desc_GER","ProductSecondary_Desc_ITA","REFTranslation_MainAprimoProduct","REFTranslation_Status","Description","ProductAll_FRA","ProductAll_GER","ProductAll_ITA","IsActive","StartDate","EndDate","REFTranslation_Type","BudgetedCost","ActualCost","ExpectedRevenue","AmountAllOpportunities","AmountWonOpportunities","ExpectedResponse","NumberSent","NumberOfContacts","NumberOfConvertedLeads","NumberOfLeads","NumberOfOpportunities","NumberOfResponses","NumberOfWonOpportunities","AprimoSGF","FlagDeleted"]}),
SAT_CURR_CustomerCoverTypeValidity_SF: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "SAT_CURR_CustomerCoverTypeValidity_SF",events: ["ValidityStartDate","ValidityEndDate","CancellationDemandDate","CancellationDate","Cancelled","CancellationReason","SalesChannel","SubscriptionCreationUser","SubscriptionContact","ReasonCode","OfferChannel","FlagDeleted"]}),
SAT_CURR_CustomerOffer_SF: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "SAT_CURR_CustomerOffer_SF",events: ["TechId_Txt","CreationDate","ExpirationDate","REFTranslation_CurrentStatus","REFTranslation_SalesChannel","Opportunity_TechId","RecordType","FlagDeleted"]}),
SAT_CURR_Invoice_Zuora: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "SAT_CURR_Invoice_Zuora",events: ["TechID_Txt","TechID","InvoiceStatus","InvoiceDate","FlagDeleted"]}),
SAT_CURR_CustomerCoverTypeOffer_SF: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "SAT_CURR_CustomerCoverTypeOffer_SF",events: ["TechId_Txt","VehicleNumber","REFTranslation_Reason","REFTranslation_CreationEvent","TheoreticalStartDate","FlagDeleted"]}),
SAT_CURR_CampaignProgram_SF: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "SAT_CURR_CampaignProgram_SF",events: ["TechID_Txt","Name","IsActive","StartDate","EndDate","StatusCode","REFTranslation_CampaignStatus","REFTranslation_Fct_CampaignSGF","SGF_FRA","SGF_GER","SGF_ITA","REFTranslation_CampaignType","Description","REFTranslation_CampaignClass","REFTranslation_CampaignPurpose","REFTranslation_CampaignCategory","FlagDeleted"]}),
SAT_CURR_Charge_Zuora: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "SAT_CURR_Charge_Zuora",events: ["ChargeAmountExclTaxes","ChargeTaxAmount","ChargeAmountInclTaxes","FlagDeleted","ChargeType"]}),
SAT_CURR_Partner_SF: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "SAT_CURR_Partner_SF",events: ["TechID_Txt","Name","FlagDeleted"]}),
SAT_CURR_CustomerCoverType_Quality: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "SAT_CURR_CustomerCoverType_Quality",events: ["T_001_001","T_001_002","T_002_001","T_002_002","T_003_001","T_004_001"]}),
SAT_CURR_CustomerCoverType_Zuora: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "SAT_CURR_CustomerCoverType_Zuora",events: ["Beneficiary","CoverType","TechID","TechID_TXT","FlagDeleted"]}),
SAT_CURR_CustomerCoverType_SF: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "SAT_CURR_CustomerCoverType_SF",events: ["Beneficiary","CoverType","TechID_Txt","FlagDeleted"]}),
SAT_CURR_CustomerProduct_SF: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "SAT_CURR_CustomerProduct_SF",events: ["Seniority","InitialStartDate","FlagActive"]}),
SAT_CURR_CustomerProductH1_SF: new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "SAT_CURR_CustomerProductH1_SF",events: ["Seniority","InitialStartDate","SeniorityReconciled","InitialStartDateReconciled","FlagActive"]})

};


graph.addCells(states);

//states.s2.embed(states.s4);

var transitons = [
new uml.Transition({ source: { id: states.HUB_CustomerProductH2.id }, target: { id: states.SAT_CURR_CustomerProductH2_SF.id }}),
new uml.Transition({ source: { id: states.HUB_Account.id }, target: { id: states.SAT_CURR_Account_SF.id }}),
new uml.Transition({ source: { id: states.HUB_Account.id }, target: { id: states.SAT_CURD_Account_BillingAddress_SF.id }}),
new uml.Transition({ source: { id: states.HUB_Account.id }, target: { id: states.SAT_CURD_Account_LegalAddress_SF.id }}),
new uml.Transition({ source: { id: states.HUB_Account.id }, target: { id: states.SAT_CURD_Account_SF.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerProductH3.id }, target: { id: states.SAT_CURR_CustomerProductH3_SF.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverTypeEvent.id }, target: { id: states.SAT_CURR_CustomerCoverTypeEvent_SF.id }}),
new uml.Transition({ source: { id: states.HUB_Product.id }, target: { id: states.SAT_CURR_Product_Zuora.id }}),
new uml.Transition({ source: { id: states.HUB_CoverType.id }, target: { id: states.SAT_CURR_CoverType_Zuora.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverTypeTerm.id }, target: { id: states.SAT_CURR_CustomerCoverTypeTerm_SF.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverTypeTerm.id }, target: { id: states.SAT_CURR_CustomerCoverTypeTerm_Zuora.id }}),
new uml.Transition({ source: { id: states.HUB_User.id }, target: { id: states.SAT_CURR_User_SF.id }}),
new uml.Transition({ source: { id: states.HUB_CampaignSegment.id }, target: { id: states.SAT_CURR_CampaignSegment_SF.id }}),
new uml.Transition({ source: { id: states.HUB_CampaignActivity.id }, target: { id: states.SAT_CURR_CampaignActivity_SF.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverTypeValidity.id }, target: { id: states.SAT_CURR_CustomerCoverTypeValidity_SF.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerOffer.id }, target: { id: states.SAT_CURR_CustomerOffer_SF.id }}),
new uml.Transition({ source: { id: states.HUB_Invoice.id }, target: { id: states.SAT_CURR_Invoice_Zuora.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverTypeOffer.id }, target: { id: states.SAT_CURR_CustomerCoverTypeOffer_SF.id }}),
new uml.Transition({ source: { id: states.HUB_CampaignProgram.id }, target: { id: states.SAT_CURR_CampaignProgram_SF.id }}),
new uml.Transition({ source: { id: states.HUB_Charge.id }, target: { id: states.SAT_CURR_Charge_Zuora.id }}),
new uml.Transition({ source: { id: states.HUB_Partner.id }, target: { id: states.SAT_CURR_Partner_SF.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverType.id }, target: { id: states.SAT_CURR_CustomerCoverType_Quality.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverType.id }, target: { id: states.SAT_CURR_CustomerCoverType_Zuora.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverType.id }, target: { id: states.SAT_CURR_CustomerCoverType_SF.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerProduct.id }, target: { id: states.SAT_CURR_CustomerProduct_SF.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerProductH1.id }, target: { id: states.SAT_CURR_CustomerProductH1_SF.id }}),

new uml.Transition({ source: { id: states.HUB_CustomerProductH2.id }, target: { id: states.LNK_CCT_CPR_CH3_CH2_CH1_Head_Bene_CT_save.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerProductH2.id }, target: { id: states.LNK_CCT_CPR_CH3_CH2_CH1_Head_Bene_CT.id }}),
new uml.Transition({ source: { id: states.HUB_Account.id }, target: { id: states.HLNK_Account_HouseholdRelationship.id }}),
new uml.Transition({ source: { id: states.HUB_Account.id }, target: { id: states.LNK_Account_CampaignActivity.id }}),
new uml.Transition({ source: { id: states.HUB_Account.id }, target: { id: states.LNK_CCTE_CCTT_CCTV_CCT_Beneficiary_CoverType_Product.id }}),
new uml.Transition({ source: { id: states.HUB_Account.id }, target: { id: states.LNK_CustomerCoverType_Account_Beneficiary.id }}),
new uml.Transition({ source: { id: states.HUB_Account.id }, target: { id: states.LNK_CCTT_CCTV_CCT_Beneficiary_CoverType_Product.id }}),
new uml.Transition({ source: { id: states.HUB_Account.id }, target: { id: states.LNK_CustomerCoverType_Account_Head.id }}),
new uml.Transition({ source: { id: states.HUB_Account.id }, target: { id: states.LNK_Invoice_Account.id }}),
new uml.Transition({ source: { id: states.HUB_Account.id }, target: { id: states.LNK_Account_CampaignSegment.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerProductH3.id }, target: { id: states.LNK_CCT_CPR_CH3_CH2_CH1_Head_Bene_CT_save.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerProductH3.id }, target: { id: states.LNK_CCT_CPR_CH3_CH2_CH1_Head_Bene_CT.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverTypeEvent.id }, target: { id: states.LNK_CustomerCoverTypeEvent_Charge_Invoice.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverTypeEvent.id }, target: { id: states.LNK_CustomerCoverTypeEvent_CampaignActivity.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverTypeEvent.id }, target: { id: states.LNK_CustomerCoverTypeEvent_CampaignSegment.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverTypeEvent.id }, target: { id: states.LNK_CustomerCoverTypeEvent_CustomerCoverType.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverTypeEvent.id }, target: { id: states.LNK_CCTE_CCTT_CCTV_CCT_Beneficiary_CoverType_Product.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverTypeEvent.id }, target: { id: states.LNK_CustomerCoverTypeEvent_CustomerCoverTypeValidity.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverTypeEvent.id }, target: { id: states.LNK_CustomerCoverTypeEvent_CustomerCoverTypeTerm.id }}),
new uml.Transition({ source: { id: states.HUB_Product.id }, target: { id: states.LNK_CustomerCoverType_Product.id }}),
new uml.Transition({ source: { id: states.HUB_Product.id }, target: { id: states.LNK_CCTE_CCTT_CCTV_CCT_Beneficiary_CoverType_Product.id }}),
new uml.Transition({ source: { id: states.HUB_Product.id }, target: { id: states.LNK_CCTT_CCTV_CCT_Beneficiary_CoverType_Product.id }}),
new uml.Transition({ source: { id: states.HUB_Product.id }, target: { id: states.LNK_CoverType_Product.id }}),
new uml.Transition({ source: { id: states.HUB_CoverType.id }, target: { id: states.LNK_CCT_CPR_CH3_CH2_CH1_Head_Bene_CT_save.id }}),
new uml.Transition({ source: { id: states.HUB_CoverType.id }, target: { id: states.LNK_CCT_CPR_CH3_CH2_CH1_Head_Bene_CT.id }}),
new uml.Transition({ source: { id: states.HUB_CoverType.id }, target: { id: states.LNK_CustomerCoverType_CoverType.id }}),
new uml.Transition({ source: { id: states.HUB_CoverType.id }, target: { id: states.LNK_CCTOFF_COFF_Head_Bene_CT_CCTV_CCTT.id }}),
new uml.Transition({ source: { id: states.HUB_CoverType.id }, target: { id: states.LNK_CCTE_CCTT_CCTV_CCT_Beneficiary_CoverType_Product.id }}),
new uml.Transition({ source: { id: states.HUB_CoverType.id }, target: { id: states.LNK_CCTT_CCTV_CCT_Beneficiary_CoverType_Product.id }}),
new uml.Transition({ source: { id: states.HUB_CoverType.id }, target: { id: states.LNK_CoverType_Product.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverTypeTerm.id }, target: { id: states.LNK_CustomerCoverTypeTerm_CustomerCoverTypeValidity_CustomerCoverType.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverTypeTerm.id }, target: { id: states.LNK_CCTOFF_COFF_Head_Bene_CT_CCTV_CCTT.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverTypeTerm.id }, target: { id: states.LNK_CCTE_CCTT_CCTV_CCT_Beneficiary_CoverType_Product.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverTypeTerm.id }, target: { id: states.LNK_CustomerCoverTypeEvent_CustomerCoverTypeTerm.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverTypeTerm.id }, target: { id: states.LNK_CCTT_CCTV_CCT_Beneficiary_CoverType_Product.id }}),
new uml.Transition({ source: { id: states.HUB_User.id }, target: { id: states.LNK_COFF_User.id }}),
new uml.Transition({ source: { id: states.HUB_User.id }, target: { id: states.HLNK_User_Orga.id }}),
new uml.Transition({ source: { id: states.HUB_CampaignSegment.id }, target: { id: states.LNK_CustomerCoverTypeEvent_CampaignSegment.id }}),
new uml.Transition({ source: { id: states.HUB_CampaignSegment.id }, target: { id: states.LNK_CCTOFF_CampaignSegment.id }}),
new uml.Transition({ source: { id: states.HUB_CampaignSegment.id }, target: { id: states.LNK_CampaignSegment_CampaignActivity.id }}),
new uml.Transition({ source: { id: states.HUB_CampaignSegment.id }, target: { id: states.LNK_Account_CampaignSegment.id }}),
new uml.Transition({ source: { id: states.HUB_CampaignActivity.id }, target: { id: states.LNK_Account_CampaignActivity.id }}),
new uml.Transition({ source: { id: states.HUB_CampaignActivity.id }, target: { id: states.LNK_CustomerCoverTypeEvent_CampaignActivity.id }}),
new uml.Transition({ source: { id: states.HUB_CampaignActivity.id }, target: { id: states.LNK_CCTOFF_CampaignActivity.id }}),
new uml.Transition({ source: { id: states.HUB_CampaignActivity.id }, target: { id: states.LNK_CampaignSegment_CampaignActivity.id }}),
new uml.Transition({ source: { id: states.HUB_CampaignActivity.id }, target: { id: states.LNK_CampaignActivity_CampaignProgram.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverTypeValidity.id }, target: { id: states.LNK_CustomerCoverTypeValidity_CustomerCoverType.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverTypeValidity.id }, target: { id: states.LNK_CustomerCoverTypeTerm_CustomerCoverTypeValidity_CustomerCoverType.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverTypeValidity.id }, target: { id: states.LNK_CCTOFF_COFF_Head_Bene_CT_CCTV_CCTT.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverTypeValidity.id }, target: { id: states.LNK_CCTE_CCTT_CCTV_CCT_Beneficiary_CoverType_Product.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverTypeValidity.id }, target: { id: states.LNK_CustomerCoverTypeEvent_CustomerCoverTypeValidity.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverTypeValidity.id }, target: { id: states.LNK_CCTT_CCTV_CCT_Beneficiary_CoverType_Product.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerOffer.id }, target: { id: states.LNK_COFF_Partner.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerOffer.id }, target: { id: states.LNK_COFF_User.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerOffer.id }, target: { id: states.LNK_CCTOFF_COFF_Head_Bene_CT_CCTV_CCTT.id }}),
new uml.Transition({ source: { id: states.HUB_Invoice.id }, target: { id: states.LNK_CustomerCoverTypeEvent_Charge_Invoice.id }}),
new uml.Transition({ source: { id: states.HUB_Invoice.id }, target: { id: states.LNK_Invoice_Account.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverTypeOffer.id }, target: { id: states.LNK_CCTOFF_CampaignActivity.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverTypeOffer.id }, target: { id: states.LNK_CCTOFF_CampaignSegment.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverTypeOffer.id }, target: { id: states.LNK_CCTOFF_COFF_Head_Bene_CT_CCTV_CCTT.id }}),
new uml.Transition({ source: { id: states.HUB_CampaignProgram.id }, target: { id: states.LNK_CampaignActivity_CampaignProgram.id }}),
new uml.Transition({ source: { id: states.HUB_Charge.id }, target: { id: states.LNK_CustomerCoverTypeEvent_Charge_Invoice.id }}),
new uml.Transition({ source: { id: states.HUB_Partner.id }, target: { id: states.LNK_COFF_Partner.id }}),
new uml.Transition({ source: { id: states.HUB_Partner.id }, target: { id: states.HLNK_Partner_Orga.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverType.id }, target: { id: states.LNK_CCT_CPR_CH3_CH2_CH1_Head_Bene_CT_save.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverType.id }, target: { id: states.LNK_CCT_CPR_CH3_CH2_CH1_Head_Bene_CT.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverType.id }, target: { id: states.LNK_CustomerCoverTypeValidity_CustomerCoverType.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverType.id }, target: { id: states.LNK_CustomerCoverTypeTerm_CustomerCoverTypeValidity_CustomerCoverType.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverType.id }, target: { id: states.LNK_CustomerCoverType_CoverType.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverType.id }, target: { id: states.LNK_CustomerCoverType_Product.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverType.id }, target: { id: states.LNK_CustomerCoverTypeEvent_CustomerCoverType.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverType.id }, target: { id: states.LNK_CCTE_CCTT_CCTV_CCT_Beneficiary_CoverType_Product.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverType.id }, target: { id: states.LNK_CustomerCoverType_Account_Beneficiary.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverType.id }, target: { id: states.LNK_CCTT_CCTV_CCT_Beneficiary_CoverType_Product.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerCoverType.id }, target: { id: states.LNK_CustomerCoverType_Account_Head.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerProduct.id }, target: { id: states.LNK_CCT_CPR_CH3_CH2_CH1_Head_Bene_CT_save.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerProduct.id }, target: { id: states.LNK_CCT_CPR_CH3_CH2_CH1_Head_Bene_CT.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerProductH1.id }, target: { id: states.LNK_CCT_CPR_CH3_CH2_CH1_Head_Bene_CT_save.id }}),
new uml.Transition({ source: { id: states.HUB_CustomerProductH1.id }, target: { id: states.LNK_CCT_CPR_CH3_CH2_CH1_Head_Bene_CT.id }})
];

graph.addCells(transitons);

var graphLayout = new joint.layout.ForceDirected({
	graph: graph,
	width: 3000, height: 3000,
	gravityCenter: { x: 1500, y: 1500 },
	charge: 2000,
	linkDistance: 250
});
graphLayout.start();

function animate() {
	joint.util.nextFrame(animate);
	graphLayout.step();
}

$('#btn-layout').on('click', animate);