CREATE DATABASE [BI_FMK] ON  PRIMARY 
( NAME = N'BI_FMK', FILENAME = N'G:\MSSQL\DATA\BI_FMK.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BI_FMK_log', FILENAME = N'L:\mssql\log\BI_FMK.LDF' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO