/* Generation des hub */
SELECT 'HUB' as Type_Objet, TABLE_NAME AS Nom, TABLE_NAME+': new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "'+TABLE_NAME+'"}),'
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'hub'
  AND TABLE_TYPE = 'BASE TABLE'
  -- AND TABLE_NAME LIKE '%ACCOUNT%'
ORDER BY TABLE_NAME

/* Generation des links */
SELECT 'LNK' as Type_Objet, TABLE_NAME AS Nom, TABLE_NAME+': new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "'+TABLE_NAME+'"}),'
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'lnk'
  AND TABLE_TYPE = 'BASE TABLE'
  -- AND TABLE_NAME LIKE '%ACCOUNT%'
ORDER BY TABLE_NAME

/* Generation des satellites */
DECLARE @Hub VARCHAR(50)
DECLARE @Satellite VARCHAR(50)
DECLARE @Champ VARCHAR(100)
DECLARE @ListeChamps VARCHAR(5000)

DECLARE sat_cursor CURSOR FOR 
SELECT HUB.TABLE_NAME AS Hub, SAT.TABLE_NAME AS Satellite

FROM (
SELECT TAB.TABLE_NAME AS TABLE_NAME, COL.COLUMN_NAME AS FK
FROM INFORMATION_SCHEMA.COLUMNS COL
/* Restriction sur les tables */
JOIN INFORMATION_SCHEMA.TABLES TAB
  ON COL.TABLE_CATALOG = TAB.TABLE_CATALOG
 AND COL.TABLE_SCHEMA = TAB.TABLE_SCHEMA
 AND COL.TABLE_NAME = TAB.TABLE_NAME
 AND TAB.TABLE_TYPE = 'BASE TABLE'
WHERE COL.TABLE_SCHEMA LIKE 'hub'
  AND COL.COLUMN_NAME LIKE '%_SK') HUB

/* Recherche de satellites */
LEFT JOIN (
SELECT TAB.TABLE_NAME AS TABLE_NAME, COL.COLUMN_NAME AS FK
FROM INFORMATION_SCHEMA.COLUMNS COL
/* Restriction sur les tables */
JOIN INFORMATION_SCHEMA.TABLES TAB
  ON COL.TABLE_CATALOG = TAB.TABLE_CATALOG
 AND COL.TABLE_SCHEMA = TAB.TABLE_SCHEMA
 AND COL.TABLE_NAME = TAB.TABLE_NAME
 AND TAB.TABLE_TYPE = 'BASE TABLE'
WHERE COL.TABLE_SCHEMA LIKE 'sat%'
  AND COL.COLUMN_NAME LIKE '%_SK'
) SAT
  ON SAT.FK = HUB.FK

OPEN sat_cursor

FETCH NEXT FROM sat_cursor 
INTO @Hub, @Satellite

WHILE @@FETCH_STATUS = 0
BEGIN
	
	SET @ListeChamps = ''
	
	DECLARE champs_cursor CURSOR FOR 
	SELECT COLUMN_NAME AS Attribut
	FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = @Satellite
	  AND COLUMN_NAME NOT LIKE '%_SK%'
	  AND COLUMN_NAME NOT IN ('HASHID', 'LoadNr')
	ORDER BY ORDINAL_POSITION
	
	OPEN champs_cursor

	FETCH NEXT FROM champs_cursor 
	INTO @Champ
	
	WHILE @@FETCH_STATUS = 0
	BEGIN
		
		IF @ListeChamps = ''
		BEGIN
			SET @ListeChamps = '"'+@Champ+'"'
		END
		ELSE
		BEGIN
			SET @ListeChamps = @ListeChamps + ',"'+@Champ+'"'
		END
		
		FETCH NEXT FROM champs_cursor 
		INTO @Champ
	END

	CLOSE champs_cursor;
	DEALLOCATE champs_cursor;
	
	PRINT @Satellite+': new uml.State({position: {x:100, y:100},size: {width:200, height:100},name: "'+@Satellite+'",events: ['+@ListeChamps+']}),'

    FETCH NEXT FROM sat_cursor 
	INTO @Hub, @Satellite
END 
CLOSE sat_cursor;
DEALLOCATE sat_cursor;

/* Generation des transitions satellites */
SELECT HUB.TABLE_NAME AS Hub, SAT.TABLE_NAME AS Satellite,
'new uml.Transition({ source: { id: states.'+HUB.TABLE_NAME+'.id }, target: { id: states.'+SAT.TABLE_NAME+'.id }}),'

FROM (
SELECT TAB.TABLE_NAME AS TABLE_NAME, COL.COLUMN_NAME AS FK
FROM INFORMATION_SCHEMA.COLUMNS COL
/* Restriction sur les tables */
JOIN INFORMATION_SCHEMA.TABLES TAB
  ON COL.TABLE_CATALOG = TAB.TABLE_CATALOG
 AND COL.TABLE_SCHEMA = TAB.TABLE_SCHEMA
 AND COL.TABLE_NAME = TAB.TABLE_NAME
 AND TAB.TABLE_TYPE = 'BASE TABLE'
WHERE COL.TABLE_SCHEMA LIKE 'hub'
  AND COL.COLUMN_NAME LIKE '%_SK') HUB

/* Recherche de satellites */
LEFT JOIN (
SELECT TAB.TABLE_NAME AS TABLE_NAME, COL.COLUMN_NAME AS FK
FROM INFORMATION_SCHEMA.COLUMNS COL
/* Restriction sur les tables */
JOIN INFORMATION_SCHEMA.TABLES TAB
  ON COL.TABLE_CATALOG = TAB.TABLE_CATALOG
 AND COL.TABLE_SCHEMA = TAB.TABLE_SCHEMA
 AND COL.TABLE_NAME = TAB.TABLE_NAME
 AND TAB.TABLE_TYPE = 'BASE TABLE'
WHERE COL.TABLE_SCHEMA LIKE 'sat%'
  AND COL.COLUMN_NAME LIKE '%_SK'
) SAT
  ON SAT.FK = HUB.FK

/* Generation des transitions links */
SELECT HUB.TABLE_NAME AS Hub, SAT.TABLE_NAME AS Satellite,
'new uml.Transition({ source: { id: states.'+HUB.TABLE_NAME+'.id }, target: { id: states.'+SAT.TABLE_NAME+'.id }}),'

FROM (
SELECT TAB.TABLE_NAME AS TABLE_NAME, COL.COLUMN_NAME AS FK
FROM INFORMATION_SCHEMA.COLUMNS COL
/* Restriction sur les tables */
JOIN INFORMATION_SCHEMA.TABLES TAB
  ON COL.TABLE_CATALOG = TAB.TABLE_CATALOG
 AND COL.TABLE_SCHEMA = TAB.TABLE_SCHEMA
 AND COL.TABLE_NAME = TAB.TABLE_NAME
 AND TAB.TABLE_TYPE = 'BASE TABLE'
WHERE COL.TABLE_SCHEMA LIKE 'hub'
  AND COL.COLUMN_NAME LIKE '%_SK') HUB

/* Recherche de satellites */
LEFT JOIN (
SELECT TAB.TABLE_NAME AS TABLE_NAME, COL.COLUMN_NAME AS FK
FROM INFORMATION_SCHEMA.COLUMNS COL
/* Restriction sur les tables */
JOIN INFORMATION_SCHEMA.TABLES TAB
  ON COL.TABLE_CATALOG = TAB.TABLE_CATALOG
 AND COL.TABLE_SCHEMA = TAB.TABLE_SCHEMA
 AND COL.TABLE_NAME = TAB.TABLE_NAME
 AND TAB.TABLE_TYPE = 'BASE TABLE'
WHERE COL.TABLE_SCHEMA = 'LNK'
  AND COL.COLUMN_NAME LIKE '%_SK'
) SAT
  ON SAT.FK = HUB.FK