TRUNCATE TABLE DSV.Partitions

SET IDENTITY_INSERT ON

INSERT INTO DSV.Partitions (
	   [id]
      ,[Fact]
      ,[Period]
      ,[StartD]
      ,[EndD]
      ,[SousPeriod]
      ,[ToProcess]
      ,[CreateXMLA]
      ,[UpdateXMLA]
      ,[DatabaseID]
      ,[CubeID]
      ,[MeasureGroupID]
      ,[MeasureGroupIDReference]
      ,[ChampsTableName]
      ,[CreateXMLARef]
      ,[UpdateXMLARef]
      ,[PartitionTableQuery]
      ,[ProcessAction]
      ,[ProcessActionRef]
      ,[ToProcessRef]
      ,[ProcessActionIndex]
      ,[ProcessActionRefIndex]
      ,[DataSourceID]
      ,[TypePlanif]
      ,[export_rapp]
)
SELECT [id]
      ,[Fact]
      ,[Period]
      ,[StartD]
      ,[EndD]
      ,[SousPeriod]
      ,[ToProcess]
      ,[CreateXMLA]
      ,[UpdateXMLA]
      ,[DatabaseID]
      ,[CubeID]
      ,[MeasureGroupID]
      ,[MeasureGroupIDReference]
      ,[ChampsTableName]
      ,[CreateXMLARef]
      ,[UpdateXMLARef]
      ,[PartitionTableQuery]
      ,[ProcessAction]
      ,[ProcessActionRef]
      ,[ToProcessRef]
      ,[ProcessActionIndex]
      ,[ProcessActionRefIndex]
      ,[DataSourceID]
      ,[TypePlanif]
      ,[export_rapp]
FROM dbo.partitions