/* Mise en place */
IF EXISTS(
SELECT 1
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME = 'Adm_Table_Dev'
)
BEGIN
	DROP TABLE Adm_Table_Dev
END

IF EXISTS(
SELECT 1
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME = 'Adm_Table_Prod'
)
BEGIN
	DROP TABLE Adm_Table_Prod
END

/* Executer en Dev */
SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE
INTO Adm_Table_Dev
FROM INFORMATION_SCHEMA.TABLES

SELECT TOP 0 TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE
INTO Adm_Table_Prod
FROM INFORMATION_SCHEMA.TABLES

/* Executer en Prod */
SELECT 'INSERT INTO Adm_Table_Prod SELECT '''+TABLE_CATALOG+''', '''+TABLE_SCHEMA+''', '''+TABLE_NAME+''', '''+TABLE_TYPE+''''
FROM INFORMATION_SCHEMA.TABLES

/* Executer les ordres d'insert en dev */

/* Comparer les resultats */
SELECT 'CREATE' as Action, DEV.TABLE_CATALOG, DEV.TABLE_SCHEMA, DEV.TABLE_NAME, DEV.TABLE_TYPE
FROM Adm_Table_Dev DEV
LEFT JOIN Adm_Table_Prod PRD
  ON DEV.TABLE_CATALOG = PRD.TABLE_CATALOG
 AND DEV.TABLE_SCHEMA  = PRD.TABLE_SCHEMA
 AND DEV.TABLE_NAME    = PRD.TABLE_NAME
 AND DEV.TABLE_TYPE    = PRD.TABLE_TYPE
WHERE PRD.TABLE_CATALOG IS NULL
UNION
SELECT 'DROP' as Action, PRD.TABLE_CATALOG, PRD.TABLE_SCHEMA, PRD.TABLE_NAME, PRD.TABLE_TYPE
FROM Adm_Table_Prod PRD
LEFT JOIN Adm_Table_Dev DEV
  ON DEV.TABLE_CATALOG = PRD.TABLE_CATALOG
 AND DEV.TABLE_SCHEMA  = PRD.TABLE_SCHEMA
 AND DEV.TABLE_NAME    = PRD.TABLE_NAME
 AND DEV.TABLE_TYPE    = PRD.TABLE_TYPE
WHERE DEV.TABLE_CATALOG IS NULL

/* Selectionner la liste des table effectivement a drop/create puis exporter les scripts */


Dim_BA ?
DimEtablissement ?
FactBA ?
param_exportMDX ?
Referentiel ?
