IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME = 'Periode')
BEGIN
	DROP TABLE Periode
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME = 'Periode_Theorique')
BEGIN
	DROP TABLE Periode_Theorique
END

CREATE TABLE Periode (
	idObjet int,
	DtDebut date,
	DtFin date
)

CREATE TABLE Periode_Theorique (
	idObjet int,
	DtDebut date,
	DtFin date
)

INSERT INTO Periode
SELECT 1, GETDATE(), GETDATE()+3

INSERT INTO Periode
SELECT 1, GETDATE()+5, GETDATE()+8

INSERT INTO Periode
SELECT 2, GETDATE(), GETDATE()+3

INSERT INTO Periode
SELECT 2, GETDATE()+3, GETDATE()+8

INSERT INTO Periode
SELECT 3, GETDATE(), GETDATE()+3

INSERT INTO Periode
SELECT 3, GETDATE()+2, GETDATE()+5

INSERT INTO Periode
SELECT 4, GETDATE(), GETDATE()+3

INSERT INTO Periode
SELECT 4, GETDATE(), GETDATE()+5

INSERT INTO Periode
SELECT 5, GETDATE(), GETDATE()+5

INSERT INTO Periode
SELECT 5, GETDATE(), GETDATE()+4

INSERT INTO Periode
SELECT 6, GETDATE()+1, GETDATE()+5

INSERT INTO Periode
SELECT 6, GETDATE(), GETDATE()+3

INSERT INTO Periode
SELECT 7, GETDATE()+3, GETDATE()+5

INSERT INTO Periode
SELECT 7, GETDATE(), GETDATE()+3

INSERT INTO Periode
SELECT 8, GETDATE(), GETDATE()+3

INSERT INTO Periode
SELECT 8, GETDATE()+3, GETDATE()+5

INSERT INTO Periode
SELECT 8, GETDATE()+5, GETDATE()+8

/* Periode theorique */

INSERT INTO Periode_Theorique
SELECT 1, GETDATE(), GETDATE()+3

INSERT INTO Periode_Theorique
SELECT 1, GETDATE()+5, GETDATE()+8

INSERT INTO Periode_Theorique
SELECT 2, GETDATE(), GETDATE()+8

INSERT INTO Periode_Theorique
SELECT 3, GETDATE(), GETDATE()+5

INSERT INTO Periode_Theorique
SELECT 4, GETDATE(), GETDATE()+5

INSERT INTO Periode_Theorique
SELECT 5, GETDATE(), GETDATE()+5

INSERT INTO Periode_Theorique
SELECT 6, GETDATE(), GETDATE()+5

INSERT INTO Periode_Theorique
SELECT 7, GETDATE(), GETDATE()+5

INSERT INTO Periode_Theorique
SELECT 8, GETDATE(), GETDATE()+8