SET STATISTICS IO ON
SET STATISTICS TIME ON

SELECT ID_ANNEE, IDT_FINESS, IDT_RSA, ID_DIAG_KEY
FROM (
SELECT  RSA.ID_ANNEE, RSA.IDT_FINESS, RSA.IDT_RSA, DIA.ID_DIAG_ASSOCIE AS ID_DIAG
FROM F_PMSI_MCO_DIAG DIA
JOIN F_PMSI_MCO_RSA RSA
  ON DIA.IDT_PMSI_MCO = RSA.IDT_PMSI_MCO
WHERE RSA.ID_DAS IS NULL
) RES
JOIN F_PMSI_MCO_RSA_DIAG_INT INT
ON RES.ID_DIAG = INT.ID_DIAG
ORDER BY ID_ANNEE, IDT_FINESS, IDT_RSA, ID_DIAG_KEY

SET STATISTICS IO OFF
SET STATISTICS TIME OFF


SET SHOWPLAN_ALL ON

SELECT ID_ANNEE, IDT_FINESS, IDT_RSA, ID_DIAG_KEY
FROM (
SELECT  RSA.ID_ANNEE, RSA.IDT_FINESS, RSA.IDT_RSA, DIA.ID_DIAG_ASSOCIE AS ID_DIAG
FROM F_PMSI_MCO_DIAG DIA
JOIN F_PMSI_MCO_RSA RSA
  ON DIA.IDT_PMSI_MCO = RSA.IDT_PMSI_MCO
WHERE RSA.ID_DAS IS NULL
) RES
JOIN F_PMSI_MCO_RSA_DIAG_INT INT
ON RES.ID_DIAG = INT.ID_DIAG
ORDER BY ID_ANNEE, IDT_FINESS, IDT_RSA, ID_DIAG_KEY

SET SHOWPLAN_ALL OFF
