ALTER TABLE dbo.F_PMSI_SSR_ACTE_CCAM DROP CONSTRAINT PK_F_PMSI_SSR_ACTE_CCAM
GO

ALTER TABLE dbo.F_PMSI_SSR_ACTE_CCAM ADD CONSTRAINT PK_F_PMSI_SSR_ACTE_CCAM PRIMARY KEY CLUSTERED  (
	[ID_ANNEE] ASC,
	[IDT_FINESS] ASC,
	[IDT_RHA] ASC,
	[ID_PMSI_SSR_LIG_CCAM] ASC)
  WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, 
        ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
  ON Scheme_Partition_Annee (ID_ANNEE)
GO

/*¨Pour chaque index */
USE [DWH]
GO

CREATE NONCLUSTERED INDEX [IDX_F_PMSI_SSR_RHA_ID_ANNEE] ON [dbo].[F_PMSI_SSR_RHA] 
(
	[ID_ANNEE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Scheme_Partition_Annee]([ID_ANNEE])
GO

CREATE NONCLUSTERED INDEX [IDX_F_PMSI_SSR_RHA_ID_ANNEE] ON [dbo].[F_PMSI_SSR_RHA] 
(
	[ID_ANNEE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Scheme_Partition_Annee]([ID_ANNEE])
GO

CREATE NONCLUSTERED INDEX [IDX_F_PMSI_SSR_RHA_ID_ANNEE] ON [dbo].[F_PMSI_SSR_RHA] 
(
	[ID_ANNEE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [Scheme_Partition_Annee]([ID_ANNEE])
GO